### ISSUE TITLE
incomplete sentence in documentation at 'what targets should I use'

### ISSUE THREAD

**Issue by stephenturner** [dahak-metagenomics/dahak#100]
At https://dahak-metagenomics.github.io/dahak/running_workflows/#what-targets-should-i-use

> What targets should I use?
> Users should use the build rules to trigger workflows.
> 
> The build rules require workflow configuration details to be set using Snakemake's configuration dictionary. **See**

☝️

**Comment by charlesreid1** [comment]
Fixed - line was inadvertently cut off
