### ISSUE TITLE
remove PS1 `$` prompt from copy-able commands in documentation

### ISSUE THREAD

**Issue by stephenturner** [dahak-metagenomics/dahak#101]
When I hit the "copy" button on commands in the documentation, most of them travel along with the `$` prompt. E.g. at https://dahak-metagenomics.github.io/dahak/running_workflows/#how-do-i-use-snakemake-with-singularity

```
$ SINGULARITY_BINDPATH="my_data:/data" snakemake --use-singularity <target>
```

**Comment by charlesreid1** [comment]
Thanks for pointing this out, will remove these and double-check we're being clear about when we're giving users bash commands versus other commands.

**Comment by charlesreid1** [comment]
Okay, this should be cleared up. Let me know if you see any more of the $ prefixes.
