### ISSUE TITLE
snakemake error: when timed out and snakemake became locked- Resolved

### ISSUE THREAD

**Issue by nalbright** [dahak-metagenomics/dahak#112]
Tried to run post pre trim workflow ($snakemake -p –use-singularity --configfile=config/custom_readfilt_workflow.json read_filtering_posttrim_workflow) but process timed out (computer died), then when try to attempt again I receive error: 
Error: snakemake -p --use-singularity --configfile=config/custom_readfilt_workflow.json read_filtering_posttrim_workflow
Building DAG of jobs…
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:/home/user/dahak_2018/dahak/workflows
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

Resolved: 

- $ snakemake --unlock  

- deleted content in data directory

- $ export SINGULARITY_BINDPATH="data:/data"

- snakemake -p --use-singularity --configfile=config/custom_readfilt_workflow.json read_filtering_pretrim_workflow read_filtering_posttrim_workflow

**Comment by charlesreid1** [comment]
Resolved by adding a troubleshooting page in commit f4750b592252b30f5d4735ffed8bbbe0c5ee355f on the [comparison-docs branch](https://github.com/dahak-metagenomics/dahak/pull/98/commits/f4750b592252b30f5d4735ffed8bbbe0c5ee355f)
