### ISSUE TITLE
Kaiju database is corrupted or not in .tgz format

### ISSUE THREAD

**Issue by olungu** [dahak-metagenomics/dahak#36]
### Expected behavior 
tar zxvf kaiju_index_nr_euk.tgz should untar the tarball
file kaiju_index_nr_euk.tgz should say this is a gizipped file 

### Actual behavior 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
kaiju_index_nr_euk.tgz: HTML document, ASCII text, with very long lines, with no line terminators

### Steps to reproduce the behavior 
curl -LO http://kaiju.binf.ku.dk/database/kaiju_index_nr_euk.tgz
tar zxvf kaiju_index_nr_euk.tgz
file kaiju_index_nr_euk.tgz

**Comment by brooksph** [comment]
@olungu I was able to get the database to download using these commands. I think the error message is incorrect but indicating one of two things; either the file tgz file did not download completely or there isn't enough space on your disk to unpack the file. The tar file is about 28 gb and unpacked file is 48 gb. I'm finishing up the protocol now but in my estimation, a 150 gb machine should be sufficient to complete the protocol. I will tag you for review when the protocol is complete.

**Comment by kternus** [comment]
@olungu I had trouble with this earlier too. I think my problem was due to internet connectivity problems and incomplete downloads. It's also not on a US-hosted site, so it may be blocked on certain networks. Try downloading it on a different internet connection and see if that helps!

**Comment by stephenturner** [comment]
Works for me too, at least with wget.

**Comment by slguertin** [comment]
Might it be worth it to try and mirror this on a US host, since other groups might have issues with non-US sites as well?

**Comment by olungu** [comment]
It seems the problem is our network rejecting a non-US download. On my end, it looked like the file had been downloaded, but it actually was a failed download. I've connected to our less secure network to be able to download and it's working... sort of... in the sense that it should finish in 3-4 days(!). So yeah, if there would be a  US host we could use for this, that would optimal. It'r quite possible that the end-user, being a US gotv entity would have the same restrictions we do on connecting outside of the country. Thank you everyone for your help/input!

**Comment by stephenturner** [comment]
I imagine this won't be the last time we'll have to curl/wget from or otherwise talk to a non-US server. No one wants to mirror/host a 20+ GB file, but it could be worse. Could we copy it over to OSF or S3 (USEast)? It would give us greater control over versioning/persistence.

**Comment by brooksph** [comment]
Bummer...it downloads in 20 mins on AWS. I'll check into hosting it on osf but right now the limit is 5 gbs per file. We may be able to get a waiver, however, it's worth noting that at least a few of the tools we'll be using are hosted overseas. If we have to have to host a bunch of them it may be costly and will increase maintenance burden so we should seek out alternatives.

**Comment by ctb** [comment]
I am happy to ask osf.io to do so - phil, thoughts?

**Comment by ctb** [comment]
(e-mail sent)

**Comment by stephenturner** [comment]
nice post from @ctb related to this, ICYMI.

http://ivory.idyll.org/blog/2017-osf-for-files.html

brings up a question that might have come up before. will this need to be designed to run over an air gap?

**Comment by ctb** [comment]
no reason you can't move the database over phyiscal media.  one of the goals is
to permit building of private databases, note.

**Comment by charlesreid1** [comment]
See #53 for continued discussion on topic...
