### ISSUE TITLE
Versioning containers 

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#40]
### Expected behavior 
Create versioned docker containers for the containers we've created similar to the example found here: https://quay.io/repository/biocontainers/sourmash/image/671a52e118a2a7276b7e32ce13c6adc487ddc5aba3e5188ed4c08c6327c6de4a?tab=layers

### Steps to reproduce the behavior

**Comment by charlesreid1** [comment]
Closing this, as we have incorporated a way of specifying container/software versions being pulled from quay.io/biocontainers in the Snakefiles.
