### ISSUE TITLE
Kaiju docker container 

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#41]
### Expected behavior 
Create docker container or request that the biocontainer is updated to include improvements; specifically -x and gzip compatibility.

**Comment by brooksph** [comment]
https://github.com/BioContainers/containers/issues/199

**Comment by charlesreid1** [comment]
Link to kaiju bioconda recipe: [https://github.com/bioconda/bioconda-recipes/tree/c1a5df5837f89815045fe48cb519fa1d7273d93f/recipes/kaiju](https://github.com/bioconda/bioconda-recipes/tree/c1a5df5837f89815045fe48cb519fa1d7273d93f/recipes/kaiju)

**Comment by charlesreid1** [comment]
For convenience, a cross-reference to @brooksph's pull request to fix the kaiju bioconda recipe: bioconda/bioconda-recipes#7213

**Comment by charlesreid1** [comment]
Fixed!
