### ISSUE TITLE
Use sphinx to build documentation website

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#43]
http://www.sphinx-doc.org/en/stable/

### Steps to reproduce the behavior

**Comment by charlesreid1** [comment]
Also see [davidstutz/sphinx-example](https://github.com/davidstutz/sphinx-example), which has a minimal example for a sphinx workflow.

**Comment by charlesreid1** [comment]
See [dahak-taco](https://charlesreid1.github.io/dahak-taco/), which now has a sphinx page set up in the [docs](https://github.com/charlesreid1/dahak-taco/tree/master/docs) directory.

**Comment by charlesreid1** [comment]
Gonna close this issue, since we have a documentation directory and docs are a work-in-progress.
