### ISSUE TITLE
Create taxonomic classification snakemake file

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak#45]
The instructions in the [taxonomic classification README file](https://github.com/dahak-metagenomics/dahak/blob/master/workflows/taxonomic_classification/README.md) should be converted to a Snakemake file.

**Comment by charlesreid1** [comment]
The readme instructions that should be turned into snakemake files starts [here](https://github.com/dahak-metagenomics/dahak/blob/master/workflows/taxonomic_classification/README.md#next-calculate-signatures-for-our-data).

**Comment by charlesreid1** [comment]
Some scripts useful for bootstrapping a fresh AWS node are at [dahak-yeti](https://github.com/charlesreid1/dahak-yeti) (yeti is the name I'm using for beefy AWS nodes).

**Comment by charlesreid1** [comment]
written and working:
[x] script to install python/conda/snakemake
[x] script to install singularity
[x] script to pull biocontainers
[x] script to get trimmed data
[x] script to get sequence bloom trees

debugging:
[ ] script to calculate signatures

unwritten:
[ ] script to compare signatures to database
[ ] script to download/unpack kaiju database
[ ] script to run kaiju
[ ] script to convert kaiju output to krona output
[ ] script to filter reads
[ ] script to pull krona container image
[ ] script to generate krona output

**Comment by charlesreid1** [comment]
Almost finished converting all bash shell scripts over to Python, for eventual translation into Snakemake.

Scripts mentioned below are in the [scripts](https://github.com/charlesreid1/dahak-yeti/tree/master/scripts) directory of [dahak-yeti](https://github.com/charlesreid1/dahak-yeti/).

Part 1 is the setup for the workflow:
* [run_all_part1.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/run_all_part1.sh) runs three installation scripts for pyenv, snakemake, and singularity
  * [install_pyenv.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/install_pyenv.py)
  * [install_snakemake.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/install_snakemake.py)
  * [install_singularity.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/install_singularity.py)

Part 2 is the taxonomic classification workflow:
* [run_all_part2.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/run_all_part2.sh) runs the remaining scripts in the taxonomic classification workflow
  * [prepare_biocontainers.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/prepare_biocontainers.py)
  * [get_sbt.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/get_sbt.py)
  * [get_trimmed_data.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/get_trimmed_data.py)
  * [calculate_signature.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/calculate_signatures.sh) - **need to convert to Python**
  * [unpack_kaiju.py](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/unpack_kaiju.py)

Part 2 remaining steps to test:
* [run_kaiju.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/run_kaiju.sh) - **need to pick up here**
* [kaiju_to_korona.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/kaiju_to_korona.sh)
* [filter_taxa.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/filter_taxa.sh)
* [visualize_korona.sh](https://github.com/charlesreid1/dahak-yeti/blob/master/scripts/visualize_korona.sh)

**Comment by charlesreid1** [comment]
Good news: each step of the taxonomic classification workflow is now running with Python shell scripts (subprocess, glob, etc.)! These can use some cleanup, but they have each been tested.

Next step is to create a Snakefile from these Python scripts. We still have outstanding questions about Snakemake workflows and dependencies, but for now I am going to keep the taxonomic workflow Snakemake file standalone. It can be incorporated with other workflow Snakemake files at a later time.

**Comment by charlesreid1** [comment]
Created a repository for deploying Snakemake workflows on a fresh AWS node. It's called [dahak-flot](https://github.com/charlesreid1/dahak-flot) and will contain a few directories:
* one or two illustrative Snakefiles demonstrating how to branch different workflows
* dahak workflows

(Note that dahak-flot is not the final version of any workflow, final versions of everything will be in official dahak repos.)

**Comment by charlesreid1** [comment]
As mentioned on Slack, we should take a look at the [ymp](https://github.com/epruesse/ymp/) project and take some inspiration from their [Stage](https://github.com/epruesse/ymp/blob/b8d7bf14e0bef6f83824671fc68684196374fe91/ymp/stage.py#L44) object. 

A Stage is a directory that is a self-contained group of steps, but that occurs in a particular order. The Stage object is just a wrapper around normal Snakemake rules, but it provides some magic keywords, `{:this:}`, `{:that:}`, and `{:prev:}`, for referring to the current stage's directory, as well as the directory of prior stages.

For an example of how this is used, see [bbmap.rules](http://ymp.readthedocs.io/en/stable/_snakefiles/ymp/rules/bbmap.rules.html#line-44) line 44.

This concept and the examples in ymp will definitely be useful in developing dahak workflows.

**Comment by charlesreid1** [comment]
Partially tested Snakefile for taxonomic classification has been added to the [dahak-flot](https://github.com/dahak-metagenomics/dahak-flot) repo [here](https://github.com/dahak-metagenomics/dahak-flot/blob/master/Snakefile). This implements one of many ways of organizing the Snakefile, and there are still further improvements to make...

One of the biggest challenges I've had with Snakemake is the fact that even though you have the `{}` syntax and mini-formatting language, a lot of the filenames end up being hard-coded because of the way `{variable}` in the inputs/outputs block becomes `{wildcards.variable}` in the shell/run block, or the variables need to be modified to change the output path or extension, etc.

**Comment by charlesreid1** [comment]
The current Snakefile is monolithic (every rule is in one big Snakefile). Next step is to break each rule into a separate file, and then run through the remaining tests. Once it's been verified, we'll close this issue and (finally!) have our taxonomic workflow Snakefile.

That would be a good opportunity to spend some time on the following:

* Documenting the process
  * Particularly, we should address the complication of proliferating versions of things
  * Currently: a readme with step-by-step shell commands, a shell script, a Python script, a Snakefile, etc.
  * What do we want to include in documentation?
  * Starting Sphinx workflow for documentation (addressing #43)

* Standardizing the process
  * Snakefile "best practices": get everyone's buy-in before writing lots of different Snakefiles with totally different styles
  * Settle on (first pass) method for testing workflows (schedule? AWS resources?)
  * Scripts to deploy AWS infrastructure, passing init script to machines, copying in Snakefile scripts (poss. other data as well)

* Benchmarking the process
  * Using the spy server to profile and benchmark the workflows, particularly during testing
  * Further benefits from automating AWS infrastructure

I'll expand on these ideas in the Projects section and add issues as needed, just collecting these thoughts here.

**Comment by ctb** [comment]
+1

**Comment by charlesreid1** [comment]
Completed Snakefile: [Snakefile in dahak-flot repo](https://github.com/charlesreid1/dahak-flot/blob/master/Snakefile)
