### ISSUE TITLE
Create Snakefile to reproduce analysis with McIntyre Data

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#54]
### Expected behavior 
@kternus and others have already done quite a bit of work on analyzing the McIntyre data set but we need to make this work reproducible. Create a Snakefile to replicate the analysis that was already performed.

**Comment by brooksph** [comment]
written and working:
- [X] Create rule to download data 
- [X] Create rule to calculate sourmash signatures 
- [X] Create rule to download sbt 
- [X] Create rule to download lca database 
- [X] Create rule to run sourmash gather 
- [X] Create rule to run sourmash lca gather 
- [X] Create rule to calculate unique k-mers 

debugging:
- [ ] create rule to assemble reads into contigs 
    - note: Although many of the McIntyre data sets contain paired-end reads both of ends are not always present thus MEGAHIT is failing to finish in paired-end mode. Going to run in single end mode. Next I may try to remove the terminal '/1' and/or '/2'

unwritten:
- [ ] script to download/unpack kaiju database
- [ ] rule to run kaiju (include -x which is a new feature that was not likely included in the McIntyre paper. 
- [ ]Create rule compare output of gather and lca gather

**Comment by ctb** [comment]
On Wed, Feb 14, 2018 at 06:37:55PM -0800, Phillip Brooks wrote:
> debugging:
> - [ ] create rule to assemble reads into contigs 
>     - note: Although many of the McIntyre data sets contain paired-end reads both of ends are not always present thus MEGAHIT is failing to finish in paired-end mode. Going to run in single end mode. Next I may try to remove the terminal '/1' and/or '/2'

the extract-paired-reads script from khmer can split them into PE and SE
files, and then you can use -r on megahit to include the SE files.

**Comment by brooksph** [comment]
We decided to to drop the McIntyre dataset analysis in favor of Shakya et al
