### ISSUE TITLE
Create docker image for the osf cli to leverage osf clone functionality

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#56]
If we want to continue using the osf command line client for file transfer we should create an image that we can incorporate into our workflows. For large numbers of files running `osf clone -p <project name>` seems like a better option than retrieving a bunch of direct links. Additionally, osf supports project components which allows that user to create subproject with their own unique project (-p) ID. Thus, one can download a directory containing just data instead all of the main project files.

**Comment by charlesreid1** [comment]
[Link](https://osfclient.readthedocs.io/en/stable/api/osfclient.html#osfclient.cli.clone)

> Copy all files from all storages of a project.

**Comment by charlesreid1** [comment]
Note: once there is an OSF CLI container available, changes should be made to the [dahak-flot Snakefile](https://github.com/charlesreid1/dahak-flot/blob/master/Snakefile).

**Comment by charlesreid1** [comment]
[well, well, well...](https://anaconda.org/conda-forge/osfclient)

**Comment by charlesreid1** [comment]
[bingo](https://quay.io/repository/centerforopenscience/osf?tab=tags)

```
$ docker pull quay.io/centerforopenscience/osf:master
```

**Comment by brooksph** [comment]
nice

**Comment by brooksph** [comment]
Container already exists

**Comment by charlesreid1** [comment]
The container exists, but:
- there are many "high" security vulnerabilities automatically detected in the container, which I'm sure would make our friends/end users nervous
    - whether this is a big deal or not could be debated
    - but this is the first thing you see on [quay.io](https://quay.io/repository/centerforopenscience/osf?tab=tags) osf container page
- will the user be hosting their reads on OSF? I would guess no - so the more general approach, which is currently implemented, is to provide URLs for each read sequence file.
