### ISSUE TITLE
What is 'SBT assembly'?

### ISSUE THREAD

**Issue by ctb** [dahak-metagenomics/dahak#59]
on https://github.com/dahak-metagenomics/dahak/blob/master/workflows/README.md

**Comment by charlesreid1** [comment]
SBT = sequence bloom tree, I was assuming the SBTs are typically assembled somehow, but maybe "download" or "read" is a better verb?

**Comment by brooksph** [comment]
Ooops. @charlesreid1 SBT assembly should be modified to assembly or removed completely. SBT construction will not be included as one of our workflows; however, we should provide a link to the sourmash docs where it explains how to do so.
