### ISSUE TITLE
How does one run a workflow?

### ISSUE THREAD

**Issue by ctb** [dahak-metagenomics/dahak#60]
I can't find anything linked in at https://github.com/dahak-metagenomics/dahak or https://github.com/dahak-metagenomics/dahak/blob/master/workflows/README.md - the Getting Started is about installing things, not running anything. Suggestions?

thx!

**Comment by charlesreid1** [comment]
Currently, [the workflows readme (in dahak/workflows)](https://github.com/dahak-metagenomics/dahak/tree/master/workflows) mainly includes explanations of what the workflows are, and is light on instructions. To run the actual workflows, you would go one directory level deeper into the folder corresponding to that workflow. For example, the [readme in the taxonomic classification folder (in dahak/workflows/taxonomic_classification)](https://github.com/dahak-metagenomics/dahak/tree/master/workflows/taxonomic_classification) contains a document version of the taxonomic classification workflow. 

The actual finished Snakemake file for taxonomic classification is in the [dahak-flot](https://github.com/dahak-metagenomics/dahak-flot) repository. This was split off into a separate repo with the intention of developing a single prototype workflow in that repo, and moving the workflow into dahak when it was ready. (Also, the size of dahak makes it awkward for development.) This repo also contains or will contain cloud/hpc init scripts.

Several of our next steps revolve around Snakemake and the dahak workflows. Particularly, with regards to documenting the workflows, we plan to decide on an appropriate format(s) for documentation to take (bash scripts, python scripts, Snakefiles, readme instructions), which should give us a good organizing principle for consolidating current documentation and organizing new documentation using sphinx.

**Comment by ctb** [comment]
I suggest having a quickstart, e.g. "So I want to trim some reads... what do I
do?" Right now there is no entry point at all into the repo.

Doesn't need to be a priority, but could also be something short & sweet.

**Comment by charlesreid1** [comment]
Tying into #61, it might be good to have some help functionality associated with tasks. 

Here's an example: suppose dahak offers a CLI, and suppose the user wants to trim reads. Then they can run with the trim reads flag on, and nothing else specified, and get information about how to specify the two required FASTA files, or a URL with the FASTA data (just a made-up example):

```
[user@host] $ dahak-cli --trim-reads

       __      __          __  
  ____/ /___ _/ /_  ____ _/ /__
 / __  / __ `/ __ \/ __ `/ //_/
/ /_/ / /_/ / / / / /_/ / ,<   
\__,_/\__,_/_/ /_/\__,_/_/|_|  
                              

Task: Trim Reads
Description: This task uses trimmomatic and fastqc to trim sequence data.

Error: exactly one of (--fasta1 --fasta2 | --fasta-url) must be used.

Usage: dahak-cli --trim-reads (--fasta1=PATH_TO_FASTA1 --fasta2=PATH_TO_FASTA2 | --fasta-url=FASTA_URL) 

    Optional flags: --output-file=PATH_TO_OUTPUT
```

**Comment by ctb** [comment]
suggestions:

* semi-automatic discovery of tasks/workflows
* descriptions etc kept in Snakefiles or JSON files associated with tasks/
  workflows
* easy discovery of which file(s) specify tasks/workflows

...and a good starting tutorial for experts :)

**Comment by charlesreid1** [comment]
Our plan going forward is to implement a simple/lightweight command line wrapper around Snakemake rules, which is what [dahak-taco](https://github.com/charlesreid1/dahak-taco/) is about. And with that approach, the help and quick start information belongs in readmes and markdown files and documentation - not in help provided via command line arguments.

In that spirit, I've implemented [dahak-taco sphinx documentation](https://charlesreid1.github.io/dahak-taco/). It provides the "quick start" and explanation of how everything works, plus a walkthrough page for each individual workflow. (see [docs/ dir of dahak-taco](https://github.com/charlesreid1/dahak-taco/tree/master/docs) for source.)

I added Snakemake rules into dahak-taco (see the [`rules/dahak/` directory](https://github.com/charlesreid1/dahak-taco/tree/master/rules/dahak)) in the form used in [snakemake-rules](https://github.com/percyfal/snakemake-rules), where rules are defined in `.rule` files and parameters defined in `.settings` files. Also, dahak-flot is being subsumed into dahak-taco. 

The command line interface for running dahak workflows being developed in dahak-taco, and the sphinx documentation too, is still a work in progress (adding in the remaining workflows and documentation for how to set parameters). But once it is done and we are happy with it, we can create a command line interface directory (`cli/` or `taco/`) and drop in the executable script + Snakefile materials from dahak-taco into this repository.

The same goes for the Github-hosted HTML content - we can copy the documentation in `dahak-taco/docs/` into `dahak/docs` (that is, into this repo), and add the output to the `gh-pages` branch of the dahak repo. Once we do that, the documentation for the CLI would be available at `https://dahak-metagenomics.github.io/dahak`.)

**Comment by brooksph** [comment]
Resolved via quickstart https://dahak-metagenomics.github.io/dahak/quickstart/
