### ISSUE TITLE
Read filtering walkthrough

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak#66]
Question about the read filtering walkthrough:

In the "run fastqc" step, you have the instructions:

```
mkdir qc
mkdir qc/before_trim 
cd qc/before_trim  # <-- ??

docker run -v ${PWD}:/data -it biocontainers/fastqc fastqc /data/SRR606249_subset10_1.fq.gz -o /data/qc/before_trim

docker run -v ${PWD}:/data -it biocontainers/fastqc fastqc /data/SRR606249_subset10_2.fq.gz -o /data/qc/before_trim
```

but these don't make sense - they only make sense if you strike the cd command.

But should that cd command still be executed, just after the fastqc step? Is the trimmomatic command being run from the `data/` directory, or the `data/qc/before_trim/` directory? It's unclear b/c of wildcard matching being used.

```
for filename in *_1*.fq.gz
do
    # first, make the base by removing .fq.gz using the unix program basename
    base=$(basename $filename .fq.gz)
    echo $base

    # now, construct the base2 filename by replacing _1 with _2
    base2=${base/_1/_2}
    echo $base2

    docker run -v ${PWD}:/data -it quay.io/biocontainers/trimmomatic:0.36--4 trimmomatic PE /data/${base}.fq.gz \
                /data/${base2}.fq.gz \
        /data/${base}.trim.fq.gz /data/${base}_se \
        /data/${base2}.trim.fq.gz /data/${base2}_se \
        ILLUMINACLIP:/data/TruSeq2-PE.fa:2:40:15 \
        LEADING:2 TRAILING:2 \
        SLIDINGWINDOW:4:2 \
        MINLEN:25
done
```

**Comment by charlesreid1** [comment]
[Link to relevant document](https://github.com/dahak-metagenomics/dahak/tree/master/workflows/read_filtering)

**Comment by charlesreid1** [comment]
I think I can answer my own question - although I'll note the same error occurs in the second "run fastqc" step.

Here's what's happening: the workflow runs fastqc on the data set twice, and generates two data sets, one in `qc/before_trim` and one in `qc/after_trim`. Neither of these data sets are used in later steps in the workflow covered in the remainder of the [read_filtering](https://github.com/dahak-metagenomics/dahak/tree/master/workflows/read_filtering) document.

**Comment by brooksph** [comment]
You're correct, the cd step is an error. Also correct about the outputs not being used in subsequent steps. Fastqc generates reports for read quality, nucleotide patterns, and the presence or absence of adapter sequences required to sort sequences. We are generating before and after trim reports so the user can see how trimming affects their data.

**Comment by brooksph** [comment]
Also, note that there is already a snakefile for read filtering; however, it needs to be modified to accept user-provided data sets.

**Comment by charlesreid1** [comment]
Ok - thanks for the reminder!
