### ISSUE TITLE
Figures?

### ISSUE THREAD

**Issue by kternus** [dahak-metagenomics/dahak#68]
Does anyone have requests for new figures or updates to existing figures? We have a graphic artist available to help, so please chime in if you have anything in mind!

### Expected behavior 
Figures are helpful for explaining how everything operates at a high level. 

### Actual behavior 
Existing workflow figures could use some updates.

### Steps to reproduce the behavior 
View the existing figures and imagine new ones. :)

**Comment by brooksph** [comment]
Yes!!! We should make a list. Can the graphic designer make a dahak logo? @ctb and @charlesreid1  probably has some idea but a well-equipped, battle tested, spaceship seems fitting.

**Comment by charlesreid1** [comment]
A few ideas:

* Workflow flowcharts:
    * We have some existing flowcharts from the project overview (the "Base Period Test Plan" document), but these are not really targeted at the specifics of Docker, singularity, various HPC/cloud platforms, or the inputs and outputs the user provides
    * A redesign of at least one or two workflow diagrams to better reflect the infrastructure/code layers would be a great starting point - something to really "bring the documentation together" - and possibly redesign some/all of the others
    * We may also want a diagram that explains the different "layers" of dahak - since it can be difficult at first to comprehend how all the pieces interact: the command line interface, the Snakefile, the Snakemake rules, the parameters, the software stack on the cloud machines, etc.

* Command line animations:
    * (Note: probably not something the graphic designer would work on)
    * [icholy/ttygif](https://github.com/icholy/ttygif) is a nice utility for turning command line output into an animated gif
    * This can be a big help to users to "see" a typical workflow (or steps of a workflow) being carried out as if they were watching over someone's shoulder
    * This is in the works...

As far as thematic elements go:
* spaceships
* tacos
* flying cars
* sharks (with lasers)
* etc.

**Comment by kternus** [comment]
Thanks for sharing your thoughts! I'm not sure what to say about the diverse array of emerging thematic elements, but I appreciate the enthusiasm for forward-thinking technologies and products.

Concepts that are important or potentially confusing are great candidates for figures. It usually works best if we provide the graphic artist with an initial draft for each figure, and then he can work with you to edit it from there. Please feel free to put together rough sketch(es) of what you'd like to see developed.

**Comment by stephenturner** [comment]
Don't challenge me during a boring meeting. 
![image](https://user-images.githubusercontent.com/460076/38277871-f7bef17e-3767-11e8-9fed-aaac1226dfd7.png)

**Comment by charlesreid1** [comment]
Up to this point we've mainly used [asciiflow](http://asciiflow.com/) for putting together quick diagrams (see [dahak-map](https://github.com/dahak-metagenomics/dahak-map)). It ain't pretty but it gets the job done and is easy to embed in markdown.

Style-wise, I think we should let @stephenturner's wonderful diagram be our guiding light. Also [makeitopen.com](http://makeitopen.com/) has some great diagrams and documentation pages describing the assembly of a a mobile application. Provides some nice inspiration. (Is there a nerdy data viz pinterest-like thing?)

**Comment by kternus** [comment]
@charlesreid1, I like what you did with asciiflow and dahak-map, and there's no need to make things pretty before sending a draft to the graphic designer. Whatever you can put together that conveys the idea will be fine! You can make quick diagrams with online tools, sketch it out on paper and send a photo, or draw with software available on your computer as @stephenturner demonstrated with the space shark dreaming of tacos/DNA.

**Comment by stephenturner** [comment]
In all seriousness, I've used LucidChart pretty extensively, makes workflow diagrams a piece of cake. Easier than hacking around with plain text IMHO, but that's just me. Sign up with an .edu address and you get more features without paying. https://www.lucidchart.com/pages/usecase/education

**Comment by kternus** [comment]
I can invite @charlesreid1 to view/edit a couple of our existing LucidCharts if he'd like to see how those work. It does place limits on how much I can do from a non-edu email address without paying $$, but it's free for everyone to a point.

**Comment by ctb** [comment]
We can give Charles a UC Davis e-mail address if that helps?

**Comment by kternus** [comment]
I think that's a good idea for LucidChart and other things. One of the benefits of working in academia is having access to more free resources with your .edu address!

**Comment by charlesreid1** [comment]
@kternus I will send you an email shortly from my UC Davis email account so you've got it.

**Comment by brooksph** [comment]
Does anyone have any logo ideas? @kternus I think it would be a nice addition to the 1.0 release. @ctb was inspired by the spaceship "Dahak" in the Dahak trilogy https://en.wikipedia.org/wiki/Mutineers'_Moon, I think. We should probably stay away from attempting to recreate images associated with the book but a spaceship might be good. Maybe a circular logo with some code or DNA in the background, a spaceship in the center, with Dahak Metagenomics around the outside. It could be pretty simple. @charlesreid1 suggests that we use the font awesome https://fontawesome.com logos as inspiration.

**Comment by charlesreid1** [comment]
I like the idea of flat logo design, like font-awesome does. Maybe start with a single-color icon that's an outline of the ship, then move to a fancier image if we so choose.

I like the idea of an organic-looking pod-shaped spaceship with trailing "tentacles" that become a double helix of DNA.

Sort of a cross between [this ship](http://geekxgirls.com/images/scifiships/10_most_loved_spaceships_09.jpg) and a [mon calamari cruiser](https://pre00.deviantart.net/89df/th/pre/i/2017/025/a/3/mon_calamari_shipyards_mc70_star_cruiser_by_shoguneagle-dawnrnq.jpg).

**Comment by kternus** [comment]
I'll put together an updated set of figures, and we can internally review that on our July 3rd call.
