### ISSUE TITLE
Limiting kaiju to genus-level output

### ISSUE THREAD

**Issue by kternus** [dahak-metagenomics/dahak#69]
### Expected behavior 
Kaiju can generate output that includes taxonomic classifications below the genus level. 

### Actual behavior and steps to reproduce the behavior 
The current kaiju steps in the taxonomic classification workflow will report genus-level results, along with the number of reads assigned to each genus and krona plot visualizations.

Others may have better thoughts on how to do this, but here are examples of kaiju commands that we've run in the past to generate output below the genus level:

Run kaiju:
kaiju -v -x -t /data/kaijudb/nodes.dmp -f /data/kaijudb/kaiju_db.fmi -i BMI_bmi_reads.fasta -o BMI_reads.out

Add taxon names:
addTaxonNames –t /data/kaijudb/nodes.dmp –n names.dmp –u –p –I BMI_reads.out –o BMI_reads.names.out

Generate summary kaiju report:
KaijuReport –t /data/kaijudb/nodes.dmp –n names.dmp –p –I BMI.out –r species -o BMI_reads.out.summary

**Comment by brooksph** [comment]
Hi @kternus! Thanks for pointing this out. In the example workflow the ```Generate summary kaiju report``` specifies genus with ```-r genus```. This can be set to species or maybe even strain and only affects the report, not the actual classification. I will point that out in the tutorial. Also, we will make sure that the the cli allows the user to specify the rank for the final report. I created an issue in the dahak taco repo where the snakefile currently lives https://github.com/dahak-metagenomics/dahak-taco/issues/1

**Comment by kternus** [comment]
Great, thanks @brooksph! You might also want to consider what information you'll need kaiju to output in the report for future automated scoring/benchmarking. I don't think NCBI taxonomy IDs will be reported without the addTaxonNames command, but it will output the organism name with the -r species command.

**Comment by charlesreid1** [comment]
I've updated the `-r genus` flag to be `-r {taxonomic_rank}` so the user can specify their own parameter for that. 

We don't currently have a rule that calls `addTaxonNames` so we can work that into the [`taxonomic_classification` workflow rules currently in dahak-taco](https://github.com/dahak-metagenomics/dahak-taco/tree/master/rules/taxonomic_classification).

**Comment by kternus** [comment]
I think we can close this issue if @charlesreid1 is done updating `-r {taxonomic_rank} ` and adding `addTaxonNames `?

Thanks!
