### ISSUE TITLE
Updating contribution guidelines 

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#71]
### Expected behavior 
Clear guidelines for contributing to dahak that make it clear that contributions are welcomed from everyone plus some specific language about how to contribute to the project. For example, where should they put their data, where should containers go, which tools can be part of the project. 

### Actual behavior 
We're doing a great job of making it clear that contributions are welcome from any and everyone but as @kternus pointed out it's not always clear how they can/should contribute. @titus provided the [Getting started with khmer development](https://khmer.readthedocs.io/en/v2.1.1/dev/getting-started.html) as a guide. Some additional good examples include https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/atom/atom/blob/master/CONTRIBUTING.md. 

Off the top there are several things we should add: 
- [x] tldr
- [x] Reference to a git/GitHub tutorial 
- [x] Links to how to create a GitHub account 
- [x] COC
- [x] Creating an issue 
- [x] Instructions on how to claim an issue and set up a GitHub project 
    - [x] Reference pull request checklist 
    - [x] What to do when a pull request is ready for review 
    - [x] What to do when changes are requested on a pull request 
        - [x] Pull request labels https://github.com/atom/atom/blob/master/CONTRIBUTING.md#pull-request-labels
    - [x] What to do when an issue is successfully merged 
- [x] If I want to contribute a dataset for benchmarking where should I put it? 
- [x] If I want to contribute a workflow how should I set it up?
- [x] If I want if I create a new image where should put it if I want to contribute to the project?

### Steps to reproduce the behavior

**Comment by charlesreid1** [comment]
nice work. 👍
