### ISSUE TITLE
Email or text notification (feature request)

### ISSUE THREAD

**Issue by bluegenes** [dahak-metagenomics/dahak#74]
Would be great to have dahak send an update when the pipeline finishes running

**Comment by ljcohen** [comment]
Suggestion for sending sms: https://www.fullstackpython.com/blog/send-sms-text-messages-python.html

**Comment by charlesreid1** [comment]
Okay - great idea, and I think this should be straightforward to integrate if we make it another container in the pipeline. 

One challenge with sms is you would have to set up a Twilio application using API keys, which would be private data. There might be a "Create a Twilio account and follow these steps to create an application and get a phone number for sending alerts", so we can see if there is interest there.

**Comment by bluegenes** [comment]
fyi email might be easier... (using mailx or something similar)

**Comment by charlesreid1** [comment]
end user has not requested this, and it is not part of our immediate deliverables. we can address this in the option year if the end user decides they want this feature.
