### ISSUE TITLE
Update link for singularity mirror 

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak#78]
### Expected behavior 
The first step in the GettingStarted.md under the Singularity section provides a command for grabbing the mirror and associated lists. 
### Actual behavior 
These instructions are updated frequently so we should provide a link to the Singularity docs: https://singularity.lbl.gov/install-linux

**Comment by charlesreid1** [comment]
Updated with commit dd9486a3f55dcbfdb0953473c54c90b98fc7637c. We now recommend users download and install stable releases from Github. We're assuming users will have singularity installed anyway, so these steps are primarily for those setting up a test environment or replicating an existing HPC environment. These installation steps were tested on an AWS Ubuntu 16.04 Xenial image.
