### ISSUE TITLE
Options for visualizing sourmash gather results

### ISSUE THREAD

**Issue by kternus** [dahak-metagenomics/dahak#87]
Can we provide scripts to go from the accessions reported by sourmash gather to a summary of the taxonomies of the organisms in a metagenome?

How could those taxonomies be exported and visualized by dahak users?

**Comment by ctb** [comment]
On Sat, Jun 09, 2018 at 07:45:01AM -0700, Krista Ternus wrote:
> Can we provide scripts to go from the accessions reported by sourmash gather to a summary of the taxonomies of the organisms in a metagenome?
> 
> How could those taxonomies be exported and visualized by dahak users?

I _believe_ this functionality is mostly implemented in a notebook,
here,

https://github.com/dib-lab/2018-mcintyre-output/blob/master/parse.ipynb

and "just" needs to be separated out into a library and a script or two.

The visualization of taxonomies is something there are lots of tools for;
@brooksph what is dahak using for this now, if anything?

**Comment by charlesreid1** [comment]
The taxonomic classification workflow implements the `kaiju2krona` and `kaijuReport` commands covered in the [taxonomic classification walkthrough](https://github.com/dahak-metagenomics/dahak/tree/master/workflows/taxonomic_classification), and a few different output report options for Kaiju (including `-r genus` output discussed in #69, which is not in the walkthrough but is in the Snakefiles) - although Phil may have more to add here.

**Comment by brooksph** [comment]
Yes, parse.ipynb for sourmash and krona for kaiju. I think there is an issue in the sourmash repo suggesting that we make the sourmash output compatible with krona. From the end user perspective this would be nice but I'd like to explore some alternatives first if it's a lot of effort; plus the notebook is great for now. I'm working on analyzing the Shakya dataset with parse.ipynb and I'll share it as soon as I have it.

**Comment by kternus** [comment]
It sounds like there may be a path forward in summarizing the classifications of sourmash at specific taxonomic ranks, which is great!

If there's interest in making sourmash output compatible with krona in the future, here's the required format for text or XML import - https://github.com/marbl/Krona/wiki/Importing-text-and-XML-data

For the dahak 1.0 release, I think we'll need to update our documentation to reflect the current state of the taxonomic classification workflow outputs. Attached is a draft figure along those lines.
![taxonomic_classification](https://user-images.githubusercontent.com/5553998/41877188-fce32a98-7895-11e8-81d3-a9dc0a0b5e9c.png)

**Comment by charlesreid1** [comment]
I like the layout of this workflow figure much better than the previous figure! In particular, this layout makes the multiple pathways more clear; before, we had several arrows terminating at kaiju but it was not clear where things went after that.

**Comment by kternus** [comment]
![_mondavi_illos_taxonomic_comparison_2018-06-27_1154](https://user-images.githubusercontent.com/5553998/41985636-8106eea4-79f9-11e8-9c63-d32c51b6ed25.png)

**Comment by brooksph** [comment]
Note that, contigs can also be used as input for sourmash and kaiju. We will present data on this and should include this in the write-up accompanied by tradeoffs (e.g. assembly is computationally expensive). I do not think it is necessary to modify this figure, at least not significantly.

**Comment by kternus** [comment]
@brooksph, here's an updated version that includes contigs or reads as input:

![taxonomic_classification](https://user-images.githubusercontent.com/5553998/42727506-e7c6d592-876d-11e8-8667-83aae3575972.png)
