### ISSUE TITLE
problem with kaiju step of taxonomic classification

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak#89]
### Expected behavior 

Running kaiju should create a kaiju output file. See the run kaiju step in the [walkthrough](https://github.com/dahak-metagenomics/dahak/tree/master/workflows/taxonomic_classification) (also on the snakemake branch of PR #83 [here](https://github.com/dahak-metagenomics/dahak/blob/5e7904e682edfecd15eaf8be9e46fa24caaea0f6/workflows/taxonomic_classification/Snakefile#L251)).

### Actual behavior 

A segmentation fault happens whether the kaiju command is run through Docker or Singularity (using the given commands below). Tested on AWS node, Ubuntu 16.04 Xenial image. Using kaiju version:

```
'quayurl' : 'quay.io/biocontainers/kaiju',
'version' : '1.6.1--pl5.22.0_0'
```

### Steps to reproduce the behavior 

```
wget -O SRR606249_1.trim30.fq.gz http://osf.io/qtzyk/download

wget -O SRR606249_2.trim30.fq.gz http://osf.io/dumz6/download

curl -O https://s3-us-west-1.amazonaws.com/spacegraphcats.ucdavis.edu/microbe-genbank-sbt-k51-2017.05.09.tar.gz

curl -O https://s3.amazonaws.com/dahak-project-ucdavis/kaiju/kaiju_index_nr_euk.tgz

tar -xzf data/kaiju_index_nr_euk.tgz -C data/ && rm -f data/kaiju_index_nr_euk.tgz

singularity pull kaiju.simg docker://quay.io/biocontainers/kaiju:1.6.1--pl5.22.0_0

singularity exec \
  --home /home/ubuntu/dahak/workflows/taxonomic_classification  \
  kaiju.simg \
  bash -c " set -euo pipefail; \
    kaiju -x -v -t /data/nodes.dmp \
    -f /data/kaiju_db_nr_euk.fmi \
    -i /data/SRR606249_1.trim2.fq.gz \
    -j /data/SRR606249_2.trim2.fq.gz \
    -o /data/SRR606249.kaiju_output.trim2.out -z 4"
```

(Note that the URL curl -O https://s3.amazonaws.com/dahak-project-ucdavis/kaiju/kaiju_index_nr_euk.tgz is an S3 bucket with the Kaiju .tgz file, which is faster and more polite to download from a bucket than to always download from Kaiju's servers).

(alternatively, you can also use a docker command, following the walkthrough or the dockerSnakefile in the `snakemake` branch linked to above).

The kaiju program starts, and runs for a minute or two, but always ends with a Segmentation Fault.

This is a bit tricky to debug, given that it depends on so many files, but do you see anything fishy about the kaiju command?
 
Output from snakemake log:

```
    Error in rule run_kaiju:
        jobid: 2
        output: data/SRR606249.kaiju_output.trim2.out

RuleException:
CalledProcessError in line 275 of /home/ubuntu/dahak/workflows/taxonomic_classification/Snakefile:
Command 'singularity exec --home /home/ubuntu/dahak/workflows/taxonomic_classification  /home/ubuntu/dahak/workflows/taxonomic_classification/.snakemake/singularity/589ebb255515f9b51548999bdfcbaa4b.simg bash -c " set -euo pipefail;  kaiju -x -v -t /data/nodes.dmp -f /data/kaiju_db_nr_euk.fmi -i /data/SRR606249_1.trim2.fq.gz -j /data/SRR606249_2.trim2.fq.gz -o /data/SRR606249.kaiju_output.trim2.out -z 4 "' returned non-zero exit status 139.
```

**Comment by charlesreid1** [comment]
### Additional useful info

This step was working fine 1 month ago. Also, 1 month ago the URL to the kaiju database file led directly to the kaiju database file (`kaiju_index_nr_euk.tgz`).

When I re-ran it, I did have to update the script to account for an HTTP 301 for the database link. The kaiju database file definitely moved since the script was last working; is it possible this is the cause of the script not working?

**Comment by charlesreid1** [comment]
Apparently this is a known issue - kaiju databases are occasionally updated to non-working states.

Plan:

* Try another database from this page: http://kaiju.binf.ku.dk/server
* Look for a smaller one
* Add this to an S3 bucket, and add checksum verification

**Comment by brooksph** [comment]
Related to https://github.com/dahak-metagenomics/dahak/issues/2 and https://github.com/dahak-metagenomics/dahak/issues/36

**Comment by brooksph** [comment]
Due to frequent updates in database location or incomplete downloads accompanied by the lack of an error message indicating that the database is the issue it may be useful to 1) include an error message in the workflows indicating the user should redownload the database if the next step fails or 2) force redownload if the next step fails. For the duration of the project it may be worth it to host the database on amazon (@ctb).

**Comment by ctb** [comment]
On Tue, Jun 12, 2018 at 08:18:51PM +0000, Chaz Reid wrote:
> Apparently this is a known issue - kaiju databases are occasionally updated to non-working states.

wat

**Comment by charlesreid1** [comment]
Revised:

kaiju databases are occasionally downloaded in non-working states

**Comment by charlesreid1** [comment]
Update:
* Using http://kaiju.binf.ku.dk/database/kaiju_index_nr_euk.tgz still leads to same segfault
* Using with http://kaiju.binf.ku.dk/database/kaiju_index_nr.tgz is okay
